name: My Test Workflow2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (e.g., staging, production)'
        required: true
        default: 'staging'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Print message
      run: |
        echo "Workflow executed successfully on demand"
        echo "Deploying to the ${{github.event.inputs.environment}} environment"
        git --version
        ls -al
    - name: Validate Environment Input
      run: |
        if [[ "${{ github.event.inputs.environment }}" != "staging" && "${{ github.event.inputs.environment }}" != "production" ]]; then
          echo "Error: Invalid environment input. Must be 'staging' or 'production'."
          exit 1
        fi
    - name: Auto Merge   
      env:
        GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        source_ref: ${{ github.event.inputs.environment == 'staging' && 'master' || 'test' }}
        target_branch: ${{ github.event.inputs.environment == 'staging' && 'test' || 'production' }}
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_SECRET }}
        script: |
          pwd
          cd /var/www/html/
          ls -al
          whoami
          echo 'Random sample text' > test3.txt
          echo "The PHP version is: $(php -v)"
          node -v
    - name: Push Code to Staging Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
        # Set up SSH
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${SSH_HOST} >> ~/.ssh/known_hosts
        
        # Change to your project directory and push to the staging server
        git remote add staging ${SSH_USERNAME}@${SSH_HOST}:/var/www/html/mytestcopy
        git push staging ${{ github.event.inputs.environment == 'staging' && 'test' || 'production' }}:main