name: My Test Workflow2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (e.g., staging, production)'
        required: true
        default: 'staging'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches
    - name: Print message
      run: |
        echo "Workflow executed successfully on demand"
        echo "Deploying to the ${{github.event.inputs.environment}} environment"
        git --version
        ls -al
    - name: Validate Environment Input
      run: |
        if [[ "${{ github.event.inputs.environment }}" != "staging" && "${{ github.event.inputs.environment }}" != "production" ]]; then
          echo "Error: Invalid environment input. Must be 'staging' or 'production'."
          exit 1
        fi
    - name: Auto Merge   
      env:
        GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        source_ref: ${{ github.event.inputs.environment == 'staging' && 'master' || 'test' }}
        target_branch: ${{ github.event.inputs.environment == 'staging' && 'test' || 'production' }}
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_SECRET }}
        script: |
          pwd
          ls -al
          whoami
          echo "The PHP version is: $(php -v)"
          node -v
          # Set up SSH
          cd /var/www/html/mytestcopy
          git remote -v
          git pull origin ${{ github.event.inputs.environment == 'staging' && 'test' || 'prod' }}