name: My Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Print message
      run: |
        echo "Workflow executed successfully on demand!"
        git --version
        ls -al