name: My Test Workflow2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (e.g., staging, production)'
        required: true
        default: 'staging'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Print message
      run: |
        echo "Workflow executed successfully on demand"
        echo "Deploying to the ${{github.event.inputs.environment}} environment"
        git --version
        ls -al
    - name: Auto Merge    
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ secrets.GH_SECRET }}
        source_ref: ${{ github.ref }}
        target_branch: ${{ github.event.inputs.environment == 'staging' && 'test' || 'prod' }}
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'