name: My Test Workflow2

on:
  workflow_dispatch:
    push:
      branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Print message
      run: |
        echo "Workflow executed successfully on demand"
        echo "using workflow dispatch event"
        git --version
        ls -al
    - name: Auto Merge    
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ secrets.GH_SECRET }}
        source_ref: ${{ github.ref }}
        target_branch: 'test'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'